### ISSUE TITLE
[Logic] Make sure pilotPairs dict is accurate to intended results of PFP pilot

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/Leakdown-Tester#13]
Need to verify with the full team that the logic being used in pilotPairs for the pilot-specific autoverification is accurate.

(located at LDT_Addendum.py -> pilotPairs)

Once done, release LDT V1.2.0 as stable release to use for pilot-launch testing needs

**Comment by zachll** [comment]
Looks great, I created PR #14 to do one fix and add some comments
