### ISSUE TITLE
Leakdown tester should summarize its output

### ISSUE THREAD

**Issue by zachll** [Display-Lab/Leakdown-Tester#16]
Motivation: It's not easy to see what the pipeline produces at a population level.

Proposed solution:
Create a high-level report that LT produces after a run, which includes the following summary:

1. Message templates sum from selected messages
2. Measures sum from selected messages
3. Causal pathways sum from selected messages

**Comment by mackgalante** [comment]
Changes are made in V1.3.0, see below for examples of the output when tests are run with '--report'

### Persona test summary:


![Image](https://github.com/Display-Lab/Leakdown-Tester/assets/133153871/4d609de9-d32c-436f-bb99-fe8020f87de6)



### MPOG Data excerpt summary:


![Image](https://github.com/Display-Lab/Leakdown-Tester/assets/133153871/827b60d4-9dcd-4a76-a50d-953a775984a1)

**Comment by mackgalante** [comment]
Need to add bug report for improper tracking of requests for local JSON files, low priority but present

Really happy with the aesthetics here. Once we pull through the name of the message template instead of the ID URI to Pictoralist, will look even better.
